apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: picam
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      nodeSelector:
        beansnet.net/wired: "true"
      containers:
      - name: webapp
        image: bentastic27/picam-webapp:latest
        env:
        - name: INGRESS_HOST
          value: "http://k3s-master.beansnet.net"
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 60Mi
          requests:
            memory: 30Mi

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: picam
  namespace: picam
  labels:
    app: picam
spec:
  selector:
    matchLabels:
      app: picam
  template:
    metadata:
      labels:
        app: picam
    spec:
      nodeSelector:
        beansnet.net/cam: "true"
      containers:
      - name: picam
        image: bentastic27/picam:latest
        env:
        - name: CAM_ROTATE
          value: "0"
        - name: CAM_FRAMERATE
          value: "2"
        - name: CAM_RESOLUTION
          value: "640x480"
        resources:
          limits:
            memory: 300Mi
          requests:
            memory: 200Mi
        ports:
        - containerPort: 8000
        securityContext:
          privileged: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: picam
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      nodeSelector:
        beansnet.net/wired: "true"
      containers:
      - name: proxy
        image: bentastic27/picam-proxy:latest
        ports:
        - containerPort: 80