apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: picam
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapp
  namespace: picam
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16, 10.0.0.0/8"
    traefik.ingress.kubernetes.io/rewrite-target: /
    traefik.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16, 10.0.0.0/8"
spec:
  rules:
  - http:
      paths:
      - path: /picam
        backend:
          serviceName: webapp
          servicePort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: picam
spec:
  selector:
    app: proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: proxy
  namespace: picam
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16, 10.0.0.0/8"
    traefik.ingress.kubernetes.io/rewrite-target: /
    traefik.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16, 10.0.0.0/8"
spec:
  rules:
  - http:
      paths:
      - path: /picam-proxy
        backend:
          serviceName: proxy
          servicePort: 80