apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: motion-output
  namespace: picam
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 600Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: motion
  namespace: picam
  labels:
    app: motion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motion
  template:
    metadata:
      labels:
        app: motion
    spec:
      nodeSelector:
        beansnet.net/data: "true"
      containers:
      - name: motion
        image: bentastic27/motion:latest
        volumeMounts:
        - name: output-dir
          mountPath: /var/lib/motion
      volumes:
        - name: output-dir
          persistentVolumeClaim:
            claimName: motion-output
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: motion-rotate
  namespace: picam
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/find
            - /motion
            - -type
            - f
            - -mtime
            - "+30"
            - -delete
            volumeMounts:
            - name: output-dir
              mountPath: /motion
          restartPolicy: Never
          volumes:
            - name: output-dir
              persistentVolumeClaim:
                claimName: motion-output