apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: motion-output
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.storage.mode }}
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: motion
  namespace: {{ .Release.Namespace }}
  labels:
    app: motion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motion
  template:
    metadata:
      labels:
        app: motion
    spec:
      nodeSelector:
        beansnet.net/data: "true"
      containers:
      - name: motion
        image: {{ .Values.motion.repository }}:{{ .Values.motion.tag }}
        volumeMounts:
        - name: output-dir
          mountPath: /var/lib/motion
      volumes:
        - name: output-dir
          persistentVolumeClaim:
            claimName: motion-output
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: motion-rotate
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: {{ .Values.motionRotate.repository }}:{{ .Values.motionRotate.tag }}
            args:
            - /bin/find
            - /motion
            - -type
            - f
            - -mtime
            - "+{{ .Values.motionRotate.retention }}"
            - -delete
            volumeMounts:
            - name: output-dir
              mountPath: /motion
          restartPolicy: Never
          volumes:
            - name: output-dir
              persistentVolumeClaim:
                claimName: motion-output